STATUS_BREAD = 0
STATUS_ZOOM = 1
STATUS_BAKING = 2
STATUS_SLEEP = 3
STATUS_LENGTH = 4

STATUS = [None] * STATUS_LENGTH
STATUS[STATUS_BREAD] = "zchlebokowany 🍞"
STATUS[STATUS_ZOOM] = "zooomies 😼"
STATUS[STATUS_BAKING] = "ugniata biszkopty 🍪"
STATUS[STATUS_SLEEP] = "śpi 😽💤"
